# **GROUPING**

In [14]:
import pandas as pd
import numpy as np

In [15]:
house_data = pd.read_csv("House_Rent_Dataset (1).csv")

In [16]:
house_data.head()

,Posted On,BHK,Rent,Size,Floor,Area Type,Area Locality,City,Furnishing Status,Tenant Preferred,Bathroom,Point of Contact
0,2022-05-18,2,10000,1100,Ground out of 2,Super Area,Bandel,Kolkata,Unfurnished,Bachelors/Family,2,Contact Owner
1,2022-05-13,2,20000,800,1 out of 3,Super Area,"Phool Bagan, Kankurgachi",Kolkata,Semi-Furnished,Bachelors/Family,1,Contact Owner
2,2022-05-16,2,17000,1000,1 out of 3,Super Area,Salt Lake City Sector 2,Kolkata,Semi-Furnished,Bachelors/Family,1,Contact Owner
3,2022-07-04,2,10000,800,1 out of 2,Super Area,Dumdum Park,Kolkata,Unfurnished,Bachelors/Family,1,Contact Owner
4,2022-05-09,2,7500,850,1 out of 2,Carpet Area,South Dum Dum,Kolkata,Unfurnished,Bachelors,1,Contact Owner

# *get_group*

Berfungsi untuk mengambil dataframe yang terdiri dari tiap kategori

In [17]:
area_type = house_data.groupby('Area Type')
super_area = area_type.get_group('Super Area')
super_area.head(10)

,Posted On,BHK,Rent,Size,Floor,Area Type,Area Locality,City,Furnishing Status,Tenant Preferred,Bathroom,Point of Contact
0,2022-05-18,2,10000,1100,Ground out of 2,Super Area,Bandel,Kolkata,Unfurnished,Bachelors/Family,2,Contact Owner
1,2022-05-13,2,20000,800,1 out of 3,Super Area,"Phool Bagan, Kankurgachi",Kolkata,Semi-Furnished,Bachelors/Family,1,Contact Owner
2,2022-05-16,2,17000,1000,1 out of 3,Super Area,Salt Lake City Sector 2,Kolkata,Semi-Furnished,Bachelors/Family,1,Contact Owner
3,2022-07-04,2,10000,800,1 out of 2,Super Area,Dumdum Park,Kolkata,Unfurnished,Bachelors/Family,1,Contact Owner
5,2022-04-29,2,7000,600,Ground out of 1,Super Area,Thakurpukur,Kolkata,Unfurnished,Bachelors/Family,2,Contact Owner
6,2022-06-21,2,10000,700,Ground out of 4,Super Area,Malancha,Kolkata,Unfurnished,Bachelors,2,Contact Agent
7,2022-06-21,1,5000,250,1 out of 2,Super Area,Malancha,Kolkata,Unfurnished,Bachelors,1,Contact Agent
16,2022-05-17,2,6000,600,1 out of 2,Super Area,Barasat,Kolkata,Semi-Furnished,Bachelors/Family,1,Contact Owner
17,2022-06-20,2,10000,800,Ground out of 2,Super Area,Behala,Kolkata,Unfurnished,Bachelors/Family,1,Contact Owner
19,2022-06-09,2,6000,660,1 out of 2,Super Area,Behala,Kolkata,Unfurnished,Bachelors/Family,1,Contact Owner

# *TIPE AREA*

In [18]:
house_data["Area Type"].unique()

<StringArray>
['Super Area', 'Carpet Area', 'Built Area']
Length: 3, dtype: str

In [19]:
carpet_area = area_type.get_group('Carpet Area')
carpet_area.head()

,Posted On,BHK,Rent,Size,Floor,Area Type,Area Locality,City,Furnishing Status,Tenant Preferred,Bathroom,Point of Contact
4,2022-05-09,2,7500,850,1 out of 2,Carpet Area,South Dum Dum,Kolkata,Unfurnished,Bachelors,1,Contact Owner
8,2022-06-07,2,26000,800,1 out of 2,Carpet Area,"Palm Avenue Kolkata, Ballygunge",Kolkata,Unfurnished,Bachelors,2,Contact Agent
9,2022-06-20,2,10000,1000,1 out of 3,Carpet Area,Natunhat,Kolkata,Semi-Furnished,Bachelors/Family,2,Contact Owner
10,2022-05-23,3,25000,1200,1 out of 4,Carpet Area,"Action Area 1, Rajarhat Newtown",Kolkata,Semi-Furnished,Bachelors/Family,2,Contact Agent
11,2022-06-07,1,5000,400,1 out of 1,Carpet Area,Keshtopur,Kolkata,Unfurnished,Bachelors/Family,1,Contact Agent

# *by Area Locality*

In [20]:
by_Area_Locality = house_data.groupby('Area Locality')

In [21]:
South_Dum_Dum = by_Area_Locality.get_group('Keshtopur')
South_Dum_Dum.head()

,Posted On,BHK,Rent,Size,Floor,Area Type,Area Locality,City,Furnishing Status,Tenant Preferred,Bathroom,Point of Contact
11,2022-06-07,1,5000,400,1 out of 1,Carpet Area,Keshtopur,Kolkata,Unfurnished,Bachelors/Family,1,Contact Agent
136,2022-06-23,2,5000,400,1 out of 3,Carpet Area,Keshtopur,Kolkata,Semi-Furnished,Bachelors/Family,1,Contact Owner
196,2022-05-19,1,5200,750,2 out of 4,Super Area,Keshtopur,Kolkata,Unfurnished,Bachelors/Family,1,Contact Owner
198,2022-04-29,2,9000,900,Ground out of 1,Super Area,Keshtopur,Kolkata,Unfurnished,Bachelors/Family,2,Contact Owner
313,2022-05-19,2,10000,300,Ground out of 1,Carpet Area,Keshtopur,Kolkata,Unfurnished,Bachelors,1,Contact Owner

# *MULTIPLE KEYS*

In [22]:
bandel = by_Area_Locality.get_group('Bandel')
bandel.head()

by_area_and_local = house_data.groupby(['Area Type', 'Area Locality'])
by_area_and_local.get_group(('Super Area','Keshtopur'))

,Posted On,BHK,Rent,Size,Floor,Area Type,Area Locality,City,Furnishing Status,Tenant Preferred,Bathroom,Point of Contact
196,2022-05-19,1,5200,750,2 out of 4,Super Area,Keshtopur,Kolkata,Unfurnished,Bachelors/Family,1,Contact Owner
198,2022-04-29,2,9000,900,Ground out of 1,Super Area,Keshtopur,Kolkata,Unfurnished,Bachelors/Family,2,Contact Owner
475,2022-07-06,2,7000,600,Ground out of 2,Super Area,Keshtopur,Kolkata,Unfurnished,Bachelors,1,Contact Agent

# **FUNCTION AGGREGATE**

In [23]:
house_data.groupby('Area Type')[['Rent','Bathroom']].mean().sort_values(['Rent','Bathroom'],ascending=True)

                     Rent  Bathroom
Area Type
Built Area   10500.000000  1.500000
Super Area   18673.396566  1.808258
Carpet Area  52385.897302  2.134030

In [24]:
rent_by_Area = house_data.groupby('Area Type')['Rent'].agg(['min','max','median','mean'])
rent_by_Area

              min      max   median          mean
Area Type
Built Area   6000    15000  10500.0  10500.000000
Carpet Area  1200  3500000  25000.0  52385.897302
Super Area   1500   350000  13000.0  18673.396566

In [25]:
house_data.groupby('City')['Rent'].agg(['min','max','median','mean'])

            min      max   median          mean
City
Bangalore  3500  3500000  14000.0  24966.365688
Chennai    3000   600000  14000.0  21614.092031
Delhi      2000   530000  17000.0  29461.983471
Hyderabad  1200   400000  14000.0  20555.048387
Kolkata    1500   180000   8500.0  11645.173664
Mumbai     4500  1200000  52000.0  85321.204733

# *Multiple Keys Aggregate*

In [26]:
house_data.groupby('City').agg({'Rent': ['min','max','median','mean'],'Size' : ['min','max']})

           Rent                                 Size
            min      max   median          mean  min   max
City
Bangalore  3500  3500000  14000.0  24966.365688   50  5700
Chennai    3000   600000  14000.0  21614.092031   80  6000
Delhi      2000   530000  17000.0  29461.983471   25  4000
Hyderabad  1200   400000  14000.0  20555.048387   10  8000
Kolkata    1500   180000   8500.0  11645.173664   20  4000
Mumbai     4500  1200000  52000.0  85321.204733  160  5000

# **ITERATION**

In [27]:
for group, df in by_area_and_local:
    print(f"{group[0] and group[1]} and number of rows {df.shape[0]}")

Chromepet, GST Road and number of rows 1
Seri Lingampally and number of rows 1
 in Erragadda, NH 9 and number of rows 1
 in Miyapur, NH 9 and number of rows 1
117 Residency, Chembur East and number of rows 1
2 BHK and number of rows 1
355 konnur highroad Ayanavaram and number of rows 1
5-20 Adharshnagar and number of rows 1
5000 and number of rows 1
58 block and number of rows 1
7 Bungalows Andheri West and number of rows 1
700051 and number of rows 1
90 ft road and number of rows 1
A 307 Blossom Heights and number of rows 1
A Narayanapura, Mahadevapura and number of rows 1
AGCR Enclave, Anand Vihar and number of rows 3
AGS Colony-Velachery and number of rows 1
Aarna Enclave and number of rows 1
Abbigere and number of rows 1
Abiramapuram and number of rows 1
Acharya Niketan, Mayur Vihar and number of rows 1
Acme Avenue, Kandivali West and number of rows 1
Action Area 1, Rajarhat Newtown and number of rows 1
Action Area 3, Rajarhat Newtown and number of rows 1
Adambakkam and number of rows 2
Adani Western Heights, 4 Bunglows and number of rows 1
Adani Western Heights, Andheri West and number of rows 3
Aditi Apartment, Andheri West and number of rows 1
Aditya Nagar-Vidyaranyapura, Vidyaranyapura and number of rows 1
Adityavardhan Apartment, Raheja Vihar and number of rows 1
Adyar, Sardar Patel Road and number of rows 7
Aecs Layout-Singasandra, Singasandra, Hosur Road and number of rows 2
Agarpara and number of rows 2
Agrahara Layout and number of rows 1
Ahimsa Marg, Mindspace and number of rows 1
Aims Sea View, Indralok and number of rows 1
Airport Area and number of rows 1
Airport Near Gate No. 21/2 and number of rows 1
Ajmera Bhakti Park, Bhakti Park and number of rows 7
Ajmera Treon, Bhakti Park and number of rows 1
Akkineni Homes Yousufguda and number of rows 1
Akruti Aneri, Marol and number of rows 1
Akruti Orchid Park, Sakinaka Junction and number of rows 2
Allwyn Colony and number of rows 1
Almeida Park, Turner Road and number of rows 1
Alpine Apartments, Chembur East and number of rows 1
Alpine Shapoorji Pallonji, Thakur Village, Kandivali East and number of rows 1
Alpine, Kandivali East and number of rows 1
Alta Monte, Pathanwadi and number of rows 1
Altamount Road and number of rows 1
Altavista, Chembur and number of rows 2
Altavista, Sion Trombay Road and number of rows 1
Alwal and number of rows 1
Alwarpet and number of rows 3
Alwarthirunagar and number of rows 1
Amar Colony, Lajpat Nagar and number of rows 1
Amar Nagar and number of rows 1
Amarpali Apartment and number of rows 1
Ambattur and number of rows 4
Ambattur railway station and number of rows 1
Ambedkar Colony, Yelahanka and number of rows 1
Ambika Siddhi Apartment, Ghatkopar and number of rows 1
Ambrosia Apartment, Borivali East and number of rows 1
Ameenpur and number of rows 1
Aminpur and number of rows 1
Amrutahalli and number of rows 1
Anakaputhur and number of rows 1
Anand Nagar-Khairatabad, NH 7 and number of rows 2
Anand Niketan and number of rows 2
Anand Parbat and number of rows 1
Anand niwas and number of rows 1
Anandapur and number of rows 1
Anant Bhoomi, Mahavir Nagar and number of rows 1
Andheri East and number of rows 2
Andheri West and number of rows 8
Andul and number of rows 1
Anita, Lokhandwala Twp and number of rows 1
Anjanapura and number of rows 1
Anna Nagar and number of rows 4
Anna Nagar East and number of rows 1
Anna Nagar West and number of rows 1
Anna Nagar West Extension and number of rows 2
Annapurna Apartment, Rajarhat Chowmatha and number of rows 1
Antop Hill, Wadala and number of rows 1
Anushakti Nagar and number of rows 1
Aradhana Layout, Arakere and number of rows 1
Arakere and number of rows 1
Arakere Mico Layout, Arakere and number of rows 1
Aristo Pearl Residency, Prabhadevi and number of rows 1
Arjun Garh, Aya Nagar and number of rows 1
Arjun Nagar, Safdarjung Enclave and number of rows 9
Arobindo Pally, Paschim Putiary and number of rows 1
Arumbakkam and number of rows 2
Aruna Colony and number of rows 1
Arunachalam Nagar, Madipakkam and number of rows 1
Ashok Nagar and number of rows 3
Ashok Nagar, Himayath Nagar and number of rows 2
Ashok Van and number of rows 1
Ask Nagar, Adambakkam and number of rows 1
Aspire, Kandivali East and number of rows 1
Aspire, Thakur Village, Kandivali East and number of rows 1
Attapur and number of rows 2
Attibele and number of rows 2
Attur Layout, Yelahanka New Town and number of rows 1
Atur Park, Chembur and number of rows 1
Auris Serenity, Adarsh Nagar and number of rows 1
Auris Serenity, Kanch Pada and number of rows 6
Auris Serenity, Link Road and number of rows 1
Auris Serenity, Malad West and number of rows 2
Avenue S, Santoshpur and number of rows 1
Aya Nagar and number of rows 3
Aya Nagar Extension and number of rows 1
Ayodhya Nagar, Quthbullapur and number of rows 1
Ayyappa Nagar, Pallavaram and number of rows 1
Azad Nagar Colaba and number of rows 1
B-7 veer Singh colony Budh vihar phase 2 delhi and number of rows 1
BHEL and number of rows 1
BHEL Nagar-Medavakkam and number of rows 1
BN Reddy Nagar and number of rows 1
BRAHMAPUR NEAR BANSDRONI and number of rows 1
Babusahib Palya and number of rows 1
Babusapalya and number of rows 2
Badrinath Tower, Amit Nagar and number of rows 1
Bagalakunte and number of rows 1
Baghajatin and number of rows 5
Baguiati and number of rows 3
Baishnabghata Patuli, Patuli and number of rows 1
Baishnabghata, Garia and number of rows 1
Baksara and number of rows 1
Balaji Gardens Layout, Gottigere and number of rows 1
Banashankari and number of rows 1
Banashankari Stage 3, Banashankari and number of rows 1
Banaswadi and number of rows 1
Band Stand, Bandra Band Stand and number of rows 1
Bandam Kommu and number of rows 1
Bandari Layout and number of rows 1
Bandlaguda Jagir and number of rows 3
Bandra East and number of rows 1
Bandra West and number of rows 37
Bangur Avenue, Lake Town and number of rows 1
Banjara Hills, NH 9 and number of rows 6
Banjara Layout and number of rows 1
Bannerghatta Main Road and number of rows 2
Bansdroni and number of rows 3
Bansdroni Mauza, Krishnanagar and number of rows 2
Bapu Nagar-Langar Houz and number of rows 1
Baranagar and number of rows 2
Barasat and number of rows 3
Barrackpore and number of rows 3
Baruipur and number of rows 4
Basava Nagar and number of rows 1
Basavanagudi and number of rows 1
Bata Nagar and number of rows 2
Battarahalli and number of rows 1
Bda Layout -Lingarajapuram and number of rows 1
Beach Towers, Prabhadevi and number of rows 1
Beeramguda, Ramachandra Puram, NH 9 and number of rows 5
Begumpet and number of rows 3
Begur and number of rows 1
Begur Road and number of rows 1
Behala and number of rows 4
Behala Chowrasta and number of rows 2
Benchmark Solus, Waterfield Road and number of rows 1
Benson Town and number of rows 1
Benzer Tower, Thakur Complex and number of rows 1
Ber Sarai and number of rows 1
Best Nagar Goregaon West and number of rows 1
Bettadasanapura and number of rows 1
Beverly Park and number of rows 1
Bhadrakali and number of rows 1
Bhagya Nagar Colony, Secunderabad and number of rows 2
Bhairav Residency, Mira Road and number of rows 1
Bhajanpura and number of rows 1
Bhakti Park and number of rows 2
Bhakti Park, Bhakti Park and number of rows 1
Bhandup and number of rows 1
Bhandup Village and number of rows 1
Bhandup West and number of rows 1
Bharat Ark, Andheri West and number of rows 1
Bharat Nagar, Moosapet and number of rows 1
Bharath Nagar, Porur and number of rows 1
Bhawanipur and number of rows 1
Bhel Township- Malleshwaram, Malleshwaram and number of rows 2
Bhogal, Jangpura and number of rows 1
Bhoomi Elegant, Thakur Complex and number of rows 1
Bijoygarh and number of rows 1
Bilal Nagar-Sagayapura and number of rows 1
Bindra Complex , Andheri East and number of rows 1
Birati and number of rows 6
Bisharpara and number of rows 2
Blue Monarch, Marol and number of rows 1
Boduppal, NH 2 2 and number of rows 2
Bohra Layout, Gottigere, bannerghatta main Road and number of rows 1
Bombay Dyeing Two ICC, Dadar East and number of rows 3
Bombay Dyeing Two ICC, Dadar TT Circle and number of rows 1
Bommasandra and number of rows 1
Bonhooghly and number of rows 1
Borivali East and number of rows 3
Borivali West and number of rows 3
Botanical Garden Area and number of rows 1
Bow Bazar and number of rows 1
Breach Candy and number of rows 4
Btm Layout Stage 2, BTM Layout and number of rows 2
Buddha Nagar Colony, Boduppal and number of rows 1
Budigere Cross and number of rows 1
Bunder Garden, Perambur and number of rows 1
Byatarayanapura and number of rows 1
Byculla West and number of rows 1
Byrathi and number of rows 2
CBI Colony and number of rows 1
Camelot Layout and number of rows 1
Camp Road and number of rows 1
Carter Road and number of rows 1
Celestia Spaces, Balkrishna Dadu Karade Chowk and number of rows 1
Central Area and number of rows 2
Central Avenue Road and number of rows 2
Central Bank Colony, Chromepet and number of rows 1
Century Bazaar and number of rows 1
Chak Thakurani, Thakurpukur and number of rows 1
Chakala and number of rows 2
Chakala Cigarette Factory and number of rows 1
Challenger Tower, Thakur Village, Kandivali East and number of rows 2
Chamundeshwari Layout, Arakere and number of rows 2
Chamundi Nagar, Rajajinagar and number of rows 1
Chanda Nagar and number of rows 1
Chanda Naik Nagar, Madhapur and number of rows 2
Chandanagar, NH 9 and number of rows 2
Chandannagar, Hooghly-Chinsurah and number of rows 1
Chandivali and number of rows 8
Channasandra and number of rows 1
Charkop and number of rows 3
Charkop Sector 6 and number of rows 1
Chattarpur Extension and number of rows 2
Chelekare, Kalyan Nagar, Outer Ring Road and number of rows 1
Chembarambakkam and number of rows 1
Chembur and number of rows 15
Chembur East and number of rows 4
Chembur Heights, Sindhi Society Chembur and number of rows 1
Cherlopalli TIRUPATI and number of rows 1
Chetpet, PH Road and number of rows 1
Chhattarpur and number of rows 6
Chhattarpur Enclave and number of rows 10
Chhattarpur Enclave Phase1, Chhattarpur and number of rows 1
Chikbasavnapura, Krishnarajapura and number of rows 1
Chikkabanavara and number of rows 1
Chikkasandra-Jalahalli West, Jalahalli West and number of rows 1
Chikuwadi and number of rows 1
Chinna Porur and number of rows 1
Chinnapanna Halli and number of rows 1
Chirag Nagar and number of rows 1
Chitra Vihar, Swasthya Vihar and number of rows 1
Chittaranjan Park and number of rows 1
Chittaranjan Park Block B and number of rows 1
Chittaranjan Park Block K and number of rows 1
Choolaimedu and number of rows 4
Choolaimedu High Road and number of rows 1
Chromepet, GST Road and number of rows 7
Cmbt and number of rows 1
Coffee Board Layout, Nagavara and number of rows 1
Collector Colony and number of rows 2
Conwood Astoria, Film City Road and number of rows 1
Conwood Astoria, Goregaon East and number of rows 1
Cooke Town, Cooke Town and number of rows 1
Cosmopolis Tower, Andheri West and number of rows 1
Crescent Bay Callisto, Parel and number of rows 2
Crescent Bay T3, Bhoiwada and number of rows 1
Crescent Solitaire, Sakinaka Junction and number of rows 2
Cuffe Parade and number of rows 1
Cunningham Road and number of rows 1
D.N. Nagar and number of rows 1
DB Ozone, Mira Road and number of rows 1
DB Woods, Gokuldham and number of rows 4
DDA Flat AD Block, Shalimar Bagh AD Block and number of rows 1
DDA Flats Block B3, Keshav Puram, Tri Nagar and number of rows 1
DJA Apartments, Dwarka Sector 13 and number of rows 1
DLH Orchid, Andheri West and number of rows 1
DLH Orchid, Lokhandwala Complex and number of rows 1
DNM Colony, Sanath Nagar and number of rows 1
Dadar East and number of rows 2
Dahisar East and number of rows 1
Dahisar West and number of rows 1
Dakshineswar and number of rows 1
Dakshini Pitampura and number of rows 2
Dammaiguda and number of rows 1
Dashadron Newtown Rajarhat and number of rows 1
Dashdrone and number of rows 1
Dasnagar and number of rows 1
Datta Pada and number of rows 1
Dattani Park and number of rows 1
Dayanand Vihar, Anand Vihar and number of rows 1
Deepa Appartment Turnbulls and number of rows 1
Defence Colony and number of rows 2
Defence Colony Layout and number of rows 1
Delhi estate Apartment and number of rows 1
Deonar and number of rows 1
Devanahalli and number of rows 1
Devi Karumariamman Nagar, Velachery and number of rows 1
Dhakuria and number of rows 1
Dheeraj Hill View Tower, Thakur Village, Kandivali East and number of rows 1
Dheeraj Insignia Apartment, Bandra Kurla Complex and number of rows 1
Dheeraj Kiran CHS Walad West, Sunder Nagar and number of rows 1
Dheeraj Swapna Apartment, Pali Hill and number of rows 1
Dheeraj Valley Tower, Goregaon East and number of rows 1
Dhobi Ghat- Rajajinagar and number of rows 1
Dhulapally and number of rows 1
Dilsukh Nagar, NH 9 and number of rows 1
Dina Bama Estate and number of rows 1
Dodda Banaswadi, Banaswadi and number of rows 1
Dodda Nekkundi Extension, Kartik Nagar, Outer Ring Road and number of rows 1
Doddabanahalli and number of rows 1
Doddakammanahalli and number of rows 1
Doddanekundi, Kartik Nagar and number of rows 2
Doddathoguru, Electronic City and number of rows 1
Domlur, Domlur and number of rows 1
Dori Walan and number of rows 1
Dosti Ambrosia, Wadala East and number of rows 1
Dosti Flamingo, Sewri and number of rows 1
Dr A.S. Rao Nagar and number of rows 2
Dr Mukherjee Nagar West and number of rows 1
Dr Ranga Road and number of rows 1
Dreams Complex, Bhandup West and number of rows 1
Dsk Madhuban, Sakinaka Junction and number of rows 1
Dum Dum and number of rows 2
Dum Dum Cantonment and number of rows 1
Dum Dum Heights, Jessore Road and number of rows 1
Dum Dum Metro and number of rows 4
Dumdum Park and number of rows 1
Duraisamy Nagar and number of rows 1
Dwarakapuri, Punjagutta, NH 9 and number of rows 1
Dwarka Mor and number of rows 2
Dwarka Sector 14 and number of rows 1
Dwarka Sector 23B and number of rows 1
Dwarka Sector 9 and number of rows 1
Dwarka sec 19 and number of rows 1
ECIL and number of rows 1
East Coast Road and number of rows 1
East End Apartments, Ph. 1ext near new Ashok nagar and number of rows 1
East Of Kailash and number of rows 3
East Of Ngef Layout, Bennigana Halli and number of rows 1
Eco Residency, Andheri East and number of rows 1
Egmore, PH Road and number of rows 1
Ekta Legranz, Chembur and number of rows 1
Ekta Meadows, Borivali East and number of rows 2
Ekta Nagar and number of rows 1
Ekta Parksville, Virar West and number of rows 1
Ekta Trinity, Santacruz West and number of rows 1
Electronic City and number of rows 6
Electronic City Phase 2, Electronic City and number of rows 3
Electronics City Phase 1, Electronic City and number of rows 3
Evershine Grandeur, Mindspace and number of rows 1
Evershine Millenium Paradise, Thakur Village, Kandivali East and number of rows 2
Evershine Nagar and number of rows 1
Ews Colony, BTM Layout and number of rows 1
FC Block and number of rows 1
Fartabad, Garia and number of rows 1
Fateh Nagar, Janakpuri and number of rows 1
Fci Layout, Deepanjali Nagar and number of rows 1
Film City and number of rows 2
Film City Road and number of rows 1
Film Nagar and number of rows 1
Financial District, Nanakram Guda and number of rows 5
Flora Heights, Andheri West and number of rows 1
Frazer Town and number of rows 2
Freedom Fighters Enclave and number of rows 2
Friends Colony and number of rows 1
GREEN PARK and number of rows 1
GSA Grandeur, Gokuldham and number of rows 1
Gachibowli and number of rows 12
Gachibowli CUC, Outer Ring Road and number of rows 2
Gagan Vihar, Krishna Nagar and number of rows 1
Gajularamaram and number of rows 1
Galassia, Kandarpada and number of rows 1
Ganapathipuram, Chromepet and number of rows 1
Gandhamguda, Bairagiguda and number of rows 1
Gandhi Colony, Netaji Nagar and number of rows 1
Gandhi Market and number of rows 1
Gandhi Nagar and number of rows 1
Gandhi Nagar Adyar and number of rows 1
Ganesh Nagar, Tilak Nagar and number of rows 1
Ganga Vihar and number of rows 1
Gangaram, Chandanagar, NH 9 and number of rows 1
Ganpat Niketan Apartment, Khar West and number of rows 1
Garden City University and number of rows 1
Garden View Apartment, Aarey Milk Colony and number of rows 1
Garfa and number of rows 1
Garia and number of rows 5
Garia Dhalua Nabapally and number of rows 1
Garia Station, Garia and number of rows 5
Gaurav Heights, Kandivali West and number of rows 1
Gautam Nagar and number of rows 2
Gayatri Hills, Jubilee Hills and number of rows 1
Geeta Colony and number of rows 1
Geeta Colony PRWS Block 3 And 7, Rajgarh Colony and number of rows 1
Gemstar Symphony Apartment, Kandivali West and number of rows 1
Ghatkesar, NH 2 2 and number of rows 2
Ghatkopar and number of rows 1
Ghatkopar East and number of rows 3
Ghatkopar West and number of rows 2
Ghatla and number of rows 1
Girinagar and number of rows 1
Godavari Homes, Quthbullapur and number of rows 1
Godrej Central, Chembur and number of rows 1
Godrej Platinum, Vikhroli East and number of rows 1
Godrej Prime, Chembur and number of rows 1
Godrej Serenity Mumbai, Chembur and number of rows 1
Godrej The Trees, Pirojshah Nagar and number of rows 1
Godrej The Trees, Vikhroli East and number of rows 3
Godrej Tranquil, Kandivali East and number of rows 2
Godrej Tranquil, Lokhandwala Twp and number of rows 1
Gokul Accord, Thakur Complex and number of rows 1
Gokul Apartment, Evershine Nagar and number of rows 2
Gokul Gagan, Thakur Village, Kandivali East and number of rows 1
Gokul Regency Apartment, Thakur Complex and number of rows 1
Gokuldham and number of rows 1
Gopalapuram and number of rows 3
Goregaon East and number of rows 1
Goregaon West and number of rows 9
Gottigere and number of rows 1
Govandi Station Road and number of rows 1
Gowrivakkam, Sembakkam and number of rows 1
Grant Road and number of rows 1
Greater Kailash 1 and number of rows 2
Greater Kailash 2 and number of rows 2
Green Gate Apartment, Pali Hill and number of rows 1
Green Park Apartment, Millat Nagar and number of rows 1
Green Woods Chkala, Andheri East and number of rows 2
Greenfields CHS, Andheri East and number of rows 1
Gubbalala, Subramanyapura and number of rows 1
Guduvancheri and number of rows 1
Gulmohar Road and number of rows 2
Gunjur and number of rows 1
Guru Angad Nagar West, Laxmi Nagar and number of rows 1
Gwachiwali and number of rows 1
HDIL Metropolis, 4 Bunglows and number of rows 2
HDIL Metropolis, Andheri West and number of rows 1
HDIL Premier Residences, Kurla West and number of rows 1
HMT Swarnapuri Colony and number of rows 1
HRBR Layout Block 1 and number of rows 1
Hafeezpet, NH 9 and number of rows 3
Hal Layout, Hosur Road and number of rows 1
Halasuru and number of rows 3
Halisahar Station Road, Kanchrapara and number of rows 1
Haralur Road and number of rows 1
Hari Kunj II, Sindhi Society Chembur and number of rows 1
Hari Nagar and number of rows 1
Haridevpur, Paschim Putiary and number of rows 1
Hatiara Extention and number of rows 1
Hayathnagar, NH 9 and number of rows 2
Hbr Layout Block 2, HBR Layout and number of rows 1
Hbr Layout Block 4, HBR Layout and number of rows 1
Hebbal and number of rows 10
Heena Gaurav Jewels, Gokuldham and number of rows 1
Hennur Main Road and number of rows 3
Hennur, Hennur Bagalur Road and number of rows 1
Hesaraghatta Main Road and number of rows 1
Highway Park Apartment, Kandivali East and number of rows 1
Hill Road, Bandra West and number of rows 1
Hillcrest, Andheri East and number of rows 2
Hillcrest, Chakala MIDC and number of rows 1
Himayath Nagar, NH 7 and number of rows 8
Hindmotor and number of rows 1
Hindu Colony and number of rows 1
Hiral Greens, Mira Road East and number of rows 1
Hiranandani Atlantis, Hiranandani Gardens and number of rows 2
Hiranandani Castle Rock, Hiranandani Gardens and number of rows 3
Hiranandani Castle Rock, Powai and number of rows 3
Hiranandani Gardens and number of rows 1

# **TRANSFORM**

In [28]:
house_data["median_rent_by_area"] = area_type["Rent"].transform("median")