# ***TABLE FORMAT***

In [3]:
import seaborn as sns
import pandas as pd
import numpy as np

In [4]:
flight_data = sns.load_dataset("flights")

In [64]:
flight_data.head(12)

    year month  passengers
0   1949   Jan         112
1   1949   Feb         118
2   1949   Mar         132
3   1949   Apr         129
4   1949   May         121
5   1949   Jun         135
6   1949   Jul         148
7   1949   Aug         148
8   1949   Sep         136
9   1949   Oct         119
10  1949   Nov         104
11  1949   Dec         118

In [7]:
flight_data.tail()

     year month  passengers
139  1960   Aug         606
140  1960   Sep         508
141  1960   Oct         461
142  1960   Nov         390
143  1960   Dec         432

# *Transpose*

In [6]:
flight_data.T.head()

,0,1,2,3,4,5,6,7,8,9,...,134,135,136,137,138,139,140,141,142,143
year,1949,1949,1949,1949,1949,1949,1949,1949,1949,1949,...,1960,1960,1960,1960,1960,1960,1960,1960,1960,1960
month,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,...,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec
passengers,112,118,132,129,121,135,148,148,136,119,...,419,461,472,535,622,606,508,461,390,432

In [8]:
flight_data.T.tail()

,0,1,2,3,4,5,6,7,8,9,...,134,135,136,137,138,139,140,141,142,143
year,1949,1949,1949,1949,1949,1949,1949,1949,1949,1949,...,1960,1960,1960,1960,1960,1960,1960,1960,1960,1960
month,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,...,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec
passengers,112,118,132,129,121,135,148,148,136,119,...,419,461,472,535,622,606,508,461,390,432

# *CrossTab*

In [53]:
percentage = pd.crosstab(index=flight_data['year'],
                        columns=flight_data['month'],
                        values=flight_data['passengers'],
                        aggfunc='max',
#                        margins=True,
#                        margins_name="Total",
#                        normalize='index'
)

In [54]:
percentage

month  Jan  Feb  Mar  Apr  May  Jun  Jul  Aug  Sep  Oct  Nov  Dec
year
1949   112  118  132  129  121  135  148  148  136  119  104  118
1950   115  126  141  135  125  149  170  170  158  133  114  140
1951   145  150  178  163  172  178  199  199  184  162  146  166
1952   171  180  193  181  183  218  230  242  209  191  172  194
1953   196  196  236  235  229  243  264  272  237  211  180  201
1954   204  188  235  227  234  264  302  293  259  229  203  229
1955   242  233  267  269  270  315  364  347  312  274  237  278
1956   284  277  317  313  318  374  413  405  355  306  271  306
1957   315  301  356  348  355  422  465  467  404  347  305  336
1958   340  318  362  348  363  435  491  505  404  359  310  337
1959   360  342  406  396  420  472  548  559  463  407  362  405
1960   417  391  419  461  472  535  622  606  508  461  390  432

In [ ]:
percentage = pd.crosstab(index=flight_data['year'],
                        columns=flight_data['month'],
                        values=flight_data['passengers'],
                        aggfunc='sum').round(1)
percentage['Mean'] = percentage.mean(axis=1).round(0)
percentage['Median'] = percentage.median(axis=1).round(0)
percentage['Min'] = percentage.min(axis=1).round(0)
percentage['Max'] = percentage.max(axis=1).round(0)
percentage

month,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec,Mean,Median,Min,Max
year,,,,,,,,,,,,,,,,
1949,112,118,132,129,121,135,148,148,136,119,104,118,127.0,127.0,104.0,148.0
1950,115,126,141,135,125,149,170,170,158,133,114,140,140.0,140.0,114.0,170.0
1951,145,150,178,163,172,178,199,199,184,162,146,166,170.0,170.0,145.0,199.0
1952,171,180,193,181,183,218,230,242,209,191,172,194,197.0,193.0,171.0,242.0
1953,196,196,236,235,229,243,264,272,237,211,180,201,225.0,229.0,180.0,272.0
1954,204,188,235,227,234,264,302,293,259,229,203,229,239.0,234.0,188.0,302.0
1955,242,233,267,269,270,315,364,347,312,274,237,278,284.0,274.0,233.0,364.0
1956,284,277,317,313,318,374,413,405,355,306,271,306,328.0,317.0,271.0,413.0
1957,315,301,356,348,355,422,465,467,404,347,305,336,368.0,355.0,301.0,467.0
1958,340,318,362,348,363,435,491,505,404,359,310,337,381.0,362.0,310.0,505.0
1959,360,342,406,396,420,472,548,559,463,407,362,405,428.0,407.0,342.0,559.0
1960,417,391,419,461,472,535,622,606,508,461,390,432,476.0,461.0,390.0,622.0

In [21]:
percentage.sum(axis=1)

year
1949      3040
1950      3352
1951      4084
1952      4728
1953      5400
1954      5734
1955      6816
1956      7878
1957      8842
1958      9144
1959     10280
1960     11428
Total    80726
dtype: int64

# ***.pivot_table***

In [61]:
flight_data.pivot_table( index = "year",
                        columns= "month",
                        values= "passengers",
#                        aggfunc=pd.Series.nunique,
                        aggfunc= "count"
)

month  Jan  Feb  Mar  Apr  May  Jun  Jul  Aug  Sep  Oct  Nov  Dec
year
1949     1    1    1    1    1    1    1    1    1    1    1    1
1950     1    1    1    1    1    1    1    1    1    1    1    1
1951     1    1    1    1    1    1    1    1    1    1    1    1
1952     1    1    1    1    1    1    1    1    1    1    1    1
1953     1    1    1    1    1    1    1    1    1    1    1    1
1954     1    1    1    1    1    1    1    1    1    1    1    1
1955     1    1    1    1    1    1    1    1    1    1    1    1
1956     1    1    1    1    1    1    1    1    1    1    1    1
1957     1    1    1    1    1    1    1    1    1    1    1    1
1958     1    1    1    1    1    1    1    1    1    1    1    1
1959     1    1    1    1    1    1    1    1    1    1    1    1
1960     1    1    1    1    1    1    1    1    1    1    1    1

# ***Melting***

In [58]:
melting = percentage.reset_index().melt(id_vars=['year'],
                            var_name='Bulan',
                            value_vars=['Jan'],
                            value_name='Passangers')
melting

    year Bulan  Passangers
0   1949   Jan         112
1   1950   Jan         115
2   1951   Jan         145
3   1952   Jan         171
4   1953   Jan         196
5   1954   Jan         204
6   1955   Jan         242
7   1956   Jan         284
8   1957   Jan         315
9   1958   Jan         340
10  1959   Jan         360
11  1960   Jan         417