In [ ]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import(
    StandardScaler, MinMaxScaler, RobustScaler, LabelEncoder, OneHotEncoder, OrdinalEncoder
)

In [89]:
data2 = {
    'produk':    ['A', 'B', 'C', 'D', 'E', 'F'],
    'kategori':  ['Elektronik', 'Fashion', 'Elektronik', 'Fashion', 'Elektronik', 'Fashion'],
    'rating':    ['Buruk', 'Cukup Buruk','Cukup', 'Cukup Bagus', 'Bagus', 'Sangat Bagus',],
    'harga':     [100, 5000, 800, 20000, 150, 35000],
    'terjual':   [1200, 30, 800, 15, 2000, 8]
}
df2 = pd.DataFrame(data2)
print(df2)

  produk    kategori        rating  harga  terjual
0      A  Elektronik         Buruk    100     1200
1      B     Fashion   Cukup Buruk   5000       30
2      C  Elektronik         Cukup    800      800
3      D     Fashion   Cukup Bagus  20000       15
4      E  Elektronik         Bagus    150     2000
5      F     Fashion  Sangat Bagus  35000        8

# **Tahap 0 Cek Skewness**

In [7]:
print("Skewness Harga:",df2['harga'].skew())
print("Skewness Terjual:",df2['terjual'].skew())

Skewness Harga: 1.3459159436522272
Skewness Terjual: 0.8862201914597673

# **Tahap 1 Transformation**

In [110]:
# log_harga = data2['harga'].apply(np.log) # Tidak bisa digunakan
log_harga = np.log1p(df2['harga'])
print(log_harga)
log_terjual = np.log1p(df2['terjual'])
print(log_terjual)

0     4.615121
1     8.517393
2     6.685861
3     9.903538
4     5.017280
5    10.463132
Name: harga, dtype: float64
0    7.090910
1    3.433987
2    6.685861
3    2.772589
4    7.601402
5    2.197225
Name: terjual, dtype: float64

In [111]:
log_harga = pd.Series(log_harga) # Merubah ke bentuk pandas lagi
log_terjual = pd.Series(log_terjual) # Merubah ke bentuk pandas lagi

In [127]:
print("Skewness harga SEBELUM log:", df2['harga'].skew().round(3))
print("Skewness harga SESUDAH log:", log_harga.skew().round(3))

print("Skewness terjual SEBELUM log:", df2['terjual'].skew().round(3))
print("Skewness terjual SETELAH log:", np.log1p(df2['terjual']).skew().round(3))

df2['log_harga'] = log_harga
df2['log_terjual'] = log_terjual

Skewness harga SEBELUM log: 1.346
Skewness harga SESUDAH log: -0.04
Skewness terjual SEBELUM log: 0.886
Skewness terjual SETELAH log: -0.046

# **Tahap 2 Encoding**

*RATING ENCODE*

In [113]:
df2['rating'] = df2['rating'].astype('category')
df2['rating_encode'] = df2['rating'].cat.codes
df2[['rating','rating_encode']]

         rating  rating_encode
0         Buruk              1
1   Cukup Buruk              4
2         Cukup              2
3   Cukup Bagus              3
4         Bagus              0
5  Sangat Bagus              5

In [114]:
# Ga sesuai dengan yang saya inginkan 

rating_map = {
    'Buruk' : 0,
    'Cukup Buruk' : 1,
    'Cukup' : 2,
    'Cukup Bagus' : 3,
    'Bagus' : 4,
    'Sangat Bagus' : 5,
}

df2['rating_encode'] = df2['rating'].map(rating_map)
df2[['rating','rating_encode']]

         rating rating_encode
0         Buruk             0
1   Cukup Buruk             1
2         Cukup             2
3   Cukup Bagus             3
4         Bagus             4
5  Sangat Bagus             5

*KATEGORI ENCODE*

In [115]:
df2['kategori_enc'] = (df2['kategori']=='Elektronik').astype(int)

df2[['kategori','kategori_enc']]

     kategori  kategori_enc
0  Elektronik             1
1     Fashion             0
2  Elektronik             1
3     Fashion             0
4  Elektronik             1
5     Fashion             0

In [125]:
# Kolom produk bersifat unik tidak ada pola, jadi lebih baik untuk dihilangkan saja

# df2 = df2.drop(columns='produk')
print(df2.columns.tolist())

['kategori', 'rating', 'harga', 'terjual', 'rating_encode', 'kategori_enc', 'log_harga', 'log_terjual']

In [130]:
print(df2)

     kategori        rating  harga  terjual rating_encode  kategori_enc  \
0  Elektronik         Buruk    100     1200             0             1
1     Fashion   Cukup Buruk   5000       30             1             0
2  Elektronik         Cukup    800      800             2             1
3     Fashion   Cukup Bagus  20000       15             3             0
4  Elektronik         Bagus    150     2000             4             1
5     Fashion  Sangat Bagus  35000        8             5             0

   log_harga  log_terjual
0   4.615121     7.090910
1   8.517393     3.433987
2   6.685861     6.685861
3   9.903538     2.772589
4   5.017280     7.601402
5  10.463132     2.197225

# **Tahap 3 Standardization**

Fokus kita disini ada pada kolom (log_harga, log_terjual)

In [141]:
from sklearn.preprocessing import StandardScaler
std_scaler = StandardScaler()

df2[['log_harga_std','log_terjual_std']] = std_scaler.fit_transform(df2[['log_harga','log_terjual']])

print(df2[['log_harga', 'log_terjual', 'log_harga_std','log_terjual_std']].round(3))

   log_harga  log_terjual  log_harga_std  log_terjual_std
0      4.615        7.091         -1.290            0.964
1      8.517        3.434          0.435           -0.693
2      6.686        6.686         -0.375            0.780
3      9.904        2.773          1.047           -0.992
4      5.017        7.601         -1.112            1.195
5     10.463        2.197          1.294           -1.253

In [143]:
print("Mean:", df2[['log_harga_std', 'log_terjual_std']].mean().round(10).values)
print("Std :", df2[['log_harga_std', 'log_terjual_std']].std(ddof=0).round(10).values)

Mean: [0. 0.]
Std : [1. 1.]

# **DATAFRAME FINAL**

In [144]:
df_final = df2[['kategori_enc', 'rating_encode', 'log_harga_std', 'log_terjual_std']].copy()

pd.set_option('display.float_format', '{:.3f}'.format)
print(df_final)
print("\nShape:", df_final.shape)
print("Kolom:", df_final.columns.tolist())

   kategori_enc rating_encode  log_harga_std  log_terjual_std
0             1             0         -1.290            0.964
1             0             1          0.435           -0.693
2             1             2         -0.375            0.780
3             0             3          1.047           -0.992
4             1             4         -1.112            1.195
5             0             5          1.294           -1.253

Shape: (6, 4)
Kolom: ['kategori_enc', 'rating_encode', 'log_harga_std', 'log_terjual_std']