# **STANDARDIZATION**

In [4]:
import seaborn as sns
import pandas as pd
import numpy as np
import sklearn

In [5]:
dataset = sns.load_dataset('diamonds')

dataset.head()

   carat      cut color clarity  depth  table  price     x     y     z
0   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3   0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4   0.31     Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75

In [6]:
def min_max_scaled(x):
    result = (x-x.min()) / (x.max()-x.min())
    return result

dataset[['price','carat']].apply(min_max_scaled)

          price     carat
0      0.000000  0.006237
1      0.000000  0.002079
2      0.000054  0.006237
3      0.000433  0.018711
4      0.000487  0.022869
...         ...       ...
53935  0.131427  0.108108
53936  0.131427  0.108108
53937  0.131427  0.103950
53938  0.131427  0.137214
53939  0.131427  0.114345

[53940 rows x 2 columns]

In [7]:
from sklearn.preprocessing import MinMaxScaler

In [8]:
min_max = MinMaxScaler()
hasil = min_max.fit_transform(dataset[['price','carat']])
print(hasil)

[[0.00000000e+00 6.23700624e-03]
 [0.00000000e+00 2.07900208e-03]
 [5.40628210e-05 6.23700624e-03]
 ...
 [1.31426718e-01 1.03950104e-01]
 [1.31426718e-01 1.37214137e-01]
 [1.31426718e-01 1.14345114e-01]]

In [9]:
pd.DataFrame(hasil, columns=[['price','carat']])

          price     carat
0      0.000000  0.006237
1      0.000000  0.002079
2      0.000054  0.006237
3      0.000433  0.018711
4      0.000487  0.022869
...         ...       ...
53935  0.131427  0.108108
53936  0.131427  0.108108
53937  0.131427  0.103950
53938  0.131427  0.137214
53939  0.131427  0.114345

[53940 rows x 2 columns]

In [10]:
def normal_scale(x):
    result = (x-x.mean() / x.std())
    return result

In [11]:
dataset[['price','carat']].apply(normal_scale, axis=0)

             price     carat
0       325.014197 -1.453377
1       325.014197 -1.473377
2       326.014197 -1.453377
3       333.014197 -1.393377
4       334.014197 -1.373377
...            ...       ...
53935  2756.014197 -0.963377
53936  2756.014197 -0.963377
53937  2756.014197 -0.983377
53938  2756.014197 -0.823377
53939  2756.014197 -0.933377

[53940 rows x 2 columns]

In [14]:
from sklearn.preprocessing import StandardScaler

norm_scaler = StandardScaler()
hasil2 = norm_scaler.fit_transform(dataset[['price', 'carat']])

In [16]:
pd.DataFrame(hasil2, columns=[['Price', 'Carat']])

          Price     Carat
0     -0.904095 -1.198168
1     -0.904095 -1.240361
2     -0.903844 -1.198168
3     -0.902090 -1.071587
4     -0.901839 -1.029394
...         ...       ...
53935 -0.294731 -0.164427
53936 -0.294731 -0.164427
53937 -0.294731 -0.206621
53938 -0.294731  0.130927
53939 -0.294731 -0.101137

[53940 rows x 2 columns]